image: alpine:latest

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  TF_PASSWORD: $TF_PASSWORD
  TF_STATE_NAME: $TF_STATE_NAME

before_script:
  - apk add --update curl jq
  - TERRAFORM_VERSION="1.7.5" 
  - curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin
  - terraform --version
  - rm -rf .terraform*
  - terraform init -reconfigure -backend-config="password=${TF_PASSWORD}"

stages:
  - validate
  - plan 
  - apply
  - destroy

syntaxcheck:
  stage: validate 
  script: 
    - terraform validate

dryrun:
  stage: plan
  script: 
    - terraform plan
  dependencies:
    - syntaxcheck

deploy:
  stage: apply
  script: 
    - terraform apply -auto-approve
  dependencies:
    - dryrun

destroy:
  stage: destroy
  environment:
    name: $TF_STATE_NAME
    action: stop
  when: manual 
  script:
    - terraform destroy -auto-approve
  dependencies:
    - deploy
